# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demovedio.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 593)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(13)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(25, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 693, 411))
        self.widget.setObjectName("widget")
        self.listView = QtWidgets.QListView(self.widget)
        self.listView.setGeometry(QtCore.QRect(150, 0, 541, 411))
        self.listView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listView.setObjectName("listView")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 148, 411))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_9.setLineWidth(4)
        self.label_9.setMidLineWidth(2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.lcdNumber = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout_2.addWidget(self.lcdNumber)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(4)
        self.label.setMidLineWidth(2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_8.setLineWidth(4)
        self.label_8.setMidLineWidth(2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_10.setLineWidth(4)
        self.label_10.setMidLineWidth(2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSlider_3.setProperty("value", 50)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setInvertedAppearance(False)
        self.horizontalSlider_3.setInvertedControls(False)
        self.horizontalSlider_3.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_3.setTickInterval(15)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.verticalLayout_2.addWidget(self.horizontalSlider_3)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 420, 693, 31))
        self.widget_2.setObjectName("widget_2")
        self.horizontalSlider = QtWidgets.QSlider(self.widget_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 0, 631, 31))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 51, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(660, 0, 31, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(0, 460, 693, 31))
        self.widget_3.setObjectName("widget_3")
        self.play = QtWidgets.QPushButton(self.widget_3)
        self.play.setGeometry(QtCore.QRect(0, 0, 28, 24))
        self.play.setStatusTip("")
        self.play.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"C:\Users\Yash\PycharmProjects\ppppp\images\Button-Play-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon)
        self.play.setObjectName("play")
        self.prev = QtWidgets.QPushButton(self.widget_3)
        self.prev.setGeometry(QtCore.QRect(40, 0, 28, 24))
        self.prev.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(r"C:\Users\Yash\PycharmProjects\ppppp\images\Fast-backward-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prev.setIcon(icon1)
        self.prev.setObjectName("prev")
        self.reset = QtWidgets.QPushButton(self.widget_3)
        self.reset.setGeometry(QtCore.QRect(80, 0, 28, 24))
        self.reset.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(r"C:\Users\Yash\PycharmProjects\ppppp\images\control-stop-square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset.setIcon(icon2)
        self.reset.setObjectName("reset")
        self.next = QtWidgets.QPushButton(self.widget_3)
        self.next.setGeometry(QtCore.QRect(120, 0, 28, 24))
        self.next.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(r"C:\Users\Yash\PycharmProjects\ppppp\images\Fast-forward-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon3)
        self.next.setObjectName("next")
        self.files = QtWidgets.QPushButton(self.widget_3)
        self.files.setGeometry(QtCore.QRect(160, 0, 28, 24))
        self.files.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(r"C:\Users\Yash\PycharmProjects\ppppp\images\application-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.files.setIcon(icon4)
        self.files.setCheckable(True)
        self.files.setObjectName("files")
        self.sound = QtWidgets.QPushButton(self.widget_3)
        self.sound.setGeometry(QtCore.QRect(540, 0, 28, 24))
        self.sound.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(r"C:\Users\Yash\PycharmProjects\ppppp\images\62788-speaker-low-volume-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sound.setIcon(icon5)
        self.sound.setObjectName("sound")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.widget_3)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(580, 0, 108, 31))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(0, 500, 693, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.widget_4.setFont(font)
        self.widget_4.setObjectName("widget_4")
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 611, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setGeometry(QtCore.QRect(620, 0, 71, 21))
        self.label_14.setObjectName("label_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 693, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.help=QtWidgets.QMenu(self.menubar)
        self.help.setObjectName("help")
        self.menuBackground = QtWidgets.QMenu(self.menuEdit)
        self.menuBackground.setObjectName("menuBackground")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBack = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(r"C:\Users\Yash\PycharmProjects\ppppp\images\Fast-backward-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBack.setIcon(icon6)
        self.actionBack.setObjectName("actionBack")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionOpen_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionDark_Background = QtWidgets.QAction(MainWindow)
        self.actionDark_Background.setObjectName("actionDark_Background")
        self.actionLight_Background = QtWidgets.QAction(MainWindow)
        self.actionLight_Background.setObjectName("actionLight_Background")
        self.actionIncrease_Sound = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(r"C:\Users\Yash\PycharmProjects\ppppp\images\62788-speaker-low-volume-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIncrease_Sound.setIcon(icon7)
        self.actionIncrease_Sound.setObjectName("actionIncrease_Sound")
        self.actionDecrease_Sound = QtWidgets.QAction(MainWindow)
        self.actionDecrease_Sound.setObjectName("actionDecrease_Sound")
        self.actionSilent_Sound = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(r"C:\Users\Yash\PycharmProjects\ppppp\images\Status-audio-volume-muted-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSilent_Sound.setIcon(icon8)
        self.actionSilent_Sound.setObjectName("actionSilent_Sound")
        self.actionhelp=QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionabout=QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuBackground.addAction(self.actionDark_Background)
        self.menuBackground.addAction(self.actionLight_Background)
        self.menuEdit.addAction(self.menuBackground.menuAction())
        self.menuEdit.addAction(self.actionIncrease_Sound)
        self.menuEdit.addAction(self.actionDecrease_Sound)
        self.menuEdit.addAction(self.actionSilent_Sound)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.help.addAction(self.actionhelp)
        self.help.addAction(self.actionabout)
        self.menubar.addAction(self.help.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Time:"))
        self.label.setText(_translate("MainWindow", "Search:"))
        self.lineEdit.setToolTip(_translate("MainWindow", "Search Bar"))
        self.label_8.setText(_translate("MainWindow", "Change View:"))
        self.comboBox.setToolTip(_translate("MainWindow", "List View Mode"))
        self.comboBox.setItemText(0, _translate("MainWindow", "View Mode"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Icon Mode"))
        self.label_10.setText(_translate("MainWindow", "Current Play Speed:"))
        self.label_3.setText(_translate("MainWindow", "00:00:00"))
        self.label_2.setText(_translate("MainWindow", "00:00:00"))
        self.play.setToolTip(_translate("MainWindow", "Play and Pause the media"))
        self.prev.setToolTip(_translate("MainWindow", "Previous vedio"))
        self.reset.setToolTip(_translate("MainWindow", "Stop PlayBack"))
        self.next.setToolTip(_translate("MainWindow", "Next vedio"))
        self.files.setToolTip(_translate("MainWindow", "Toggle Playlist"))
        self.sound.setToolTip(_translate("MainWindow", "Volume icon"))
        self.horizontalSlider_2.setToolTip(_translate("MainWindow", "Volume"))
        self.label_5.setToolTip(_translate("MainWindow", "Status"))
        self.label_14.setText(_translate("MainWindow", "--:--:--/--:--:--"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))

        self.help.setTitle(_translate("MainWindow","Help"))
        self.menuBackground.setTitle(_translate("MainWindow", "Background"))
        self.actionBack.setText(_translate("MainWindow", "Back"))
        self.actionBack.setShortcut(_translate("MainWindow", "Left"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionOpen_File.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionOpen_Folder.setText(_translate("MainWindow", "Open Folder"))
        self.actionOpen_Folder.setShortcut(_translate("MainWindow", "Alt+Shift+O"))
        self.actionDark_Background.setText(_translate("MainWindow", "Dark Background"))
        self.actionLight_Background.setText(_translate("MainWindow", "Light Background"))
        self.actionIncrease_Sound.setText(_translate("MainWindow", "Increase Sound"))
        self.actionIncrease_Sound.setShortcut(_translate("MainWindow", "Up"))
        self.actionDecrease_Sound.setText(_translate("MainWindow", "Decrease Sound"))
        self.actionDecrease_Sound.setShortcut(_translate("MainWindow", "Down"))
        self.actionSilent_Sound.setText(_translate("MainWindow", "Silent Sound"))
        self.actionhelp.setText(_translate("MainWindow","Help"))
        self.actionabout.setText(_translate("MainWindow","About"))
